### ISSUE TITLE
Could not mute elon musk on catalog section

### ISSUE THREAD

**Issue by gorkemuz** [peacecwz/mutty#1]
**Describe the bug**
When I try to mute elon musk through catalog section, it does not respond. When I look to the network section, I see I got an error.
**To Reproduce**
1. Go to catalogs
2. Click on categories and select elon musk
3. Click on mute button over elon musk card
4. Nothing happens

**Screenshots**
<img width="1280" alt="Screenshot 2022-08-30 at 19 03 50" src="https://user-images.githubusercontent.com/23075891/187486077-23cd642e-976f-49c6-bad5-04c0134ef6f7.png">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS M1]
 - Browser [chrome]
 - Version [104.0]

**Comment by peacecwz** [comment]
Hi,

Thanks. I created and merged a #2 PR. It's not created as a keyword file.
